### ISSUE TITLE
Channel preview scroll bar in module 0 not working

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#14] opened 2022-03-16 20:00 UTC
**Describe the bug**
After loading a .zvi file into Module 0, under the Confirm/Edit metadata menu there is the eye-shaped icon to preview each channel. Opening the preview window shows the first frame of each channel, but scrolling doesn't work; the frame number advances but the actual image doesn't move. Note that this doesn't affect downstream stuff; the channels are separated and loaded correctly in the GUI afterwards.

**To Reproduce**
1. Open CellACDC.
2. Open Module 0.
3. Load movie, using any one of "single" or "multiple" load.
4. Get to metadata screen, open channel preview, see error.

**Expected behavior**
I expected the preview to scroll through the frames like in the GUI.

**Screenshots**
[see below; frames 9 and 71 should not look the same, confirmed in FIJI]

**Desktop (please complete the following information):**
 - Python 3.9.7
 - OS: Windows 10
 - Cell-ACDC v1.2.4rc4

![frame 9](https://user-images.githubusercontent.com/99368623/158678726-769c7f52-2bb5-4c6e-8c15-18563b93b198.PNG)
![frame 71](https://user-images.githubusercontent.com/99368623/158678740-631fedc5-595c-48f1-9885-70aa14ff3366.PNG)

**Comment by ElpadoCan** [comment] 2022-03-17 07:05
Hi Jordan, this is actually expected behaviour. The preview is only for the first frame because loading the entire video would take much longer and the preview is only for checking which channel is what. However, I never realized that the scrollbar is not disabled or hidden so I will fix that before closing.

**Comment by jordanyx** [comment] 2022-03-17 18:05
Oh, gotcha! That makes sense!

**Closed** 2022-04-13 00:53 UTC
Labels: bug
